### ISSUE TITLE
Adding Shadow to Text to Improve Readability

### ISSUE THREAD

**Issue by cyouh95** [kukermichelle/bwui-capstone-placeholder#1]
I would suggest adding some shadow to the below line of text in your index page to increase the color contrast and improve readability.

```css
.hero h2 {
  text-shadow: 2px 2px 4px #000000;
  ...
}
```

https://github.com/kukermichelle/bwui-capstone-placeholder/blob/master/ware-house-starting-code/resources/css/index.css#L17
