### ISSUE TITLE
Increasing Spacing between Product Items

### ISSUE THREAD

**Issue by cyouh95** [kukermichelle/bwui-capstone-placeholder#2]
Perhaps it'd be nice to add some margins for the product images to increase spacing and reduce crowding. (For example, adding the below for your index page, etc.)

```css
.products .image-container {
  margin: 10px;
}
```

https://github.com/kukermichelle/bwui-capstone-placeholder/blob/master/ware-house-starting-code/resources/css/index.css
